site_name: Iowa City Schools Board Archive
site_description: >-
  This site is under construction.
site_url: https://b00mhauer.github.io/iowa-city-schools-board-archive/

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo

plugins: []

markdown_extensions:
  - admonition
  - attr_list

nav:
  - Home: index.md

extra:
  generator: false
