"""Auto-generate docs/timeline.md from three data sources.

This script writes the Timeline as a **chronological fact dashboard** —
events sorted newest first, each entry carrying its source citation. It
does NOT add editorial characterization; the events come from:

  1. Hand-curated anchor events (data/anchor_events_<year>.json) —
     for pre-crisis history and out-of-band facts not in the press file.
  2. Press article entries parsed from docs/press/<year>.md —
     each H3 "### \"Headline\"" with a publication and date.
  3. Meeting events from data/summaries_<year>.json — each substantive
     2026 board meeting becomes a Timeline entry.

The output is regenerated by refresh_press.py daily, so the Timeline
stays in sync with the press file automatically.

Usage:

    python scripts/build_timeline.py \\
        --press docs/press/2026.md \\
        --summaries data/summaries_2026.json \\
        --anchors data/anchor_events_2026.json \\
        --meetings-json "/.../all_meetings.json" \\
        --year 2026 \\
        --out docs/timeline.md
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime
from pathlib import Path


# Matches things like "**KCRG-TV9** — January 30, 2026" inside the press
# article entries. The press file uses bold-publication + em-dash + date.
_PRESS_META_RE = re.compile(
    r"^\*\*([^*]+?)\*\*\s*(?:—\s*([^—\n]+?))?\s*(?:—\s*\*([^*]+?)\*)?\s*$"
)

# Matches an H3 article heading line in the press file.
_H3_RE = re.compile(r"^###\s+(.+?)\s*$", re.MULTILINE)

# Date parsing helpers — the press file has dates like:
#   "January 30, 2026", "Apr 28/29", "May 12, 2026", "2026-05-26"
_MONTHS = {
    "january": 1, "february": 2, "march": 3, "april": 4, "may": 5,
    "june": 6, "july": 7, "august": 8, "september": 9, "october": 10,
    "november": 11, "december": 12,
    "jan": 1, "feb": 2, "mar": 3, "apr": 4, "jun": 6, "jul": 7,
    "aug": 8, "sep": 9, "sept": 9, "oct": 10, "nov": 11, "dec": 12,
}


def parse_press_date(s: str, default_year: int) -> tuple[str, int, int, int]:
    """Parse a press-style date into (display, year, month, day-or-0).

    Returns a sortable tuple. Day defaults to 1 when unspecified.
    """
    s = (s or "").strip().strip("—").strip(",").strip()
    if not s:
        return ("", default_year, 0, 0)

    # ISO date: 2026-05-26
    m = re.match(r"(\d{4})-(\d{1,2})(?:-(\d{1,2}))?", s)
    if m:
        y, mo, d = m.groups()
        return (s, int(y), int(mo), int(d) if d else 0)

    # "Month Day, Year" or "Month Day"
    m = re.match(r"([A-Za-z]+)\s+(\d{1,2})(?:[/](\d{1,2}))?(?:,\s*(\d{4}))?", s)
    if m:
        mo_name, d1, _d2, y = m.groups()
        mo_lower = mo_name.lower().rstrip(".")
        if mo_lower in _MONTHS:
            month = _MONTHS[mo_lower]
            day = int(d1)
            year = int(y) if y else default_year
            return (s, year, month, day)

    # Bare year-month like "2026-04" or "April 2026"
    m = re.match(r"([A-Za-z]+)\s+(\d{4})", s)
    if m:
        mo_name, y = m.groups()
        mo_lower = mo_name.lower().rstrip(".")
        if mo_lower in _MONTHS:
            return (s, int(y), _MONTHS[mo_lower], 0)

    return (s, default_year, 0, 0)


def parse_press_articles(press_md: str, year: int) -> list[dict]:
    """Walk the press markdown and extract one Timeline entry per article."""
    out: list[dict] = []
    lines = press_md.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        m_h3 = _H3_RE.match(line)
        if not m_h3:
            i += 1
            continue
        headline = m_h3.group(1).strip()
        # The next non-blank line should be the **Publication** line; the
        # one after may be the URL. We allow some flexibility.
        publication = ""
        date_str = ""
        url = ""
        # Look at the next ~6 lines for a publication line and a URL.
        for j in range(1, 8):
            if i + j >= len(lines):
                break
            ln = lines[i + j].strip()
            if not ln:
                continue
            # Publication line
            mp = _PRESS_META_RE.match(ln)
            if mp:
                publication = mp.group(1).strip()
                if mp.group(2):
                    date_str = mp.group(2).strip()
                # mp.group(3) would be the byline italic; we drop it for Timeline.
                continue
            # URL line: "[https://...](https://...)" or just a markdown link
            mu = re.search(r"\((https?://[^)\s]+)\)", ln)
            if mu and not url:
                url = mu.group(1)
            # Stop at next H2/H3
            if ln.startswith("## ") or ln.startswith("### "):
                break
        if not headline:
            i += 1
            continue
        disp, y, mo, d = parse_press_date(date_str, year)
        out.append({
            "kind": "press",
            "date_display": disp or "",
            "sort_year": y,
            "sort_month": mo,
            "sort_day": d,
            "title": headline.strip('"'),
            "publication": publication,
            "url": url,
        })
        i += 1
    return out


def parse_summary_first_sentence(s: str, max_chars: int = 280) -> str:
    """Pick a short opening clause from a meeting summary."""
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)  # strip bold
    s = s.replace("\\n", " ").replace("\n", " ").strip()
    m = re.search(r"^(.+?[.!?])(\s|$)", s)
    if m:
        out = m.group(1).strip()
    else:
        out = s
    if len(out) > max_chars:
        out = out[:max_chars].rsplit(" ", 1)[0] + "…"
    return out


def collect_meeting_events(summaries: dict, all_meetings: list[dict],
                            year: int) -> list[dict]:
    """One Timeline entry per summarized meeting."""
    titles_by_mid: dict[int, dict] = {}
    for m in all_meetings:
        if isinstance(m.get("MID"), int):
            titles_by_mid[m["MID"]] = m
    out: list[dict] = []
    for mid_str, summary_text in summaries.items():
        try:
            mid = int(mid_str)
        except ValueError:
            continue
        m = titles_by_mid.get(mid)
        if not m:
            continue
        dt = m.get("DateTime", "")
        # Expect YYYY-MM-DDTHH:MM:SS
        try:
            d = datetime.strptime(dt[:10], "%Y-%m-%d")
        except Exception:
            continue
        if d.year != year:
            continue
        title = m.get("Title", "Meeting")
        gist = parse_summary_first_sentence(summary_text)
        # slugify title for meeting-page URL
        slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:60].rstrip("-")
        out.append({
            "kind": "meeting",
            "date_display": d.strftime("%B %d, %Y"),
            "sort_year": d.year,
            "sort_month": d.month,
            "sort_day": d.day,
            "title": title,
            "summary": gist,
            "url": f"meetings/{year}/{d.strftime('%Y-%m-%d')}-{slug}.md",
        })
    return out


def collect_anchor_events(anchors: dict, year: int) -> list[dict]:
    out: list[dict] = []
    for e in anchors.get("events", []):
        ds, y, mo, d = parse_press_date(e.get("date", ""), year)
        out.append({
            "kind": "anchor",
            "date_display": ds,
            "sort_year": y,
            "sort_month": mo,
            "sort_day": d,
            "title": e.get("title", ""),
            "summary": e.get("summary", ""),
            "citations": e.get("citations", []),
        })
    return out


def render_entry(e: dict) -> str:
    """Render one Timeline entry as a markdown list item."""
    kind = e["kind"]
    date = e.get("date_display", "")
    title = e.get("title", "")
    if kind == "press":
        pub = e.get("publication", "")
        url = e.get("url", "")
        meta = f"  {pub}" + (f" — {date}" if date and date != pub else "")
        line = f"- **{date or '(undated)'}** — *Reported:* \"{title}\" — {pub}"
        if url:
            line += f" — [read article]({url})"
        return line
    if kind == "meeting":
        url = e.get("url", "")
        gist = e.get("summary", "")
        if url:
            return (
                f"- **{date}** — *Board meeting:* "
                f"[{title}]({url}) — {gist}"
            )
        return f"- **{date}** — *Board meeting:* {title} — {gist}"
    if kind == "anchor":
        summary = e.get("summary", "")
        cites = e.get("citations", [])
        cite_strs = [f"[{c['label']}]({c['url']})" for c in cites]
        cite_block = "  *Citations:* " + "; ".join(cite_strs) if cite_strs else ""
        return f"- **{date}** — {title} — {summary}{(' ' + cite_block) if cite_block else ''}"
    return f"- {title}"


def render_timeline(events: list[dict], year: int) -> str:
    """Group entries by month, newest first within each month."""
    # Sort newest first
    events.sort(key=lambda e: (
        e["sort_year"], e["sort_month"], e["sort_day"], e["kind"]
    ), reverse=True)

    out: list[str] = []
    out.append("---")
    out.append("title: Timeline")
    out.append("---")
    out.append("")
    out.append("# Timeline")
    out.append("")
    out.append(
        f"A chronological dashboard of the {year} ICCSD board record. Each "
        f"entry is one of three kinds:"
    )
    out.append("")
    out.append("- ***Board meeting:*** a meeting on the board calendar, linked to the meeting page on this archive.")
    out.append("- ***Reported:*** a news article published by a local outlet, linked to the original story.")
    out.append("- **Anchor events:** hand-curated pre-crisis facts and out-of-band events with source citations.")
    out.append("")
    out.append(
        "The Timeline is **auto-generated** from the press index, the meeting "
        "record, and the [anchor-events data file]"
        "(https://github.com/b00mhauer/iowa-city-schools-board-archive/blob/main/data/anchor_events_2026.json). "
        "It refreshes daily as the press file is updated. "
        "**No interpretive characterization is added by the site** — entries "
        "carry the source's wording (article headline, meeting title) and "
        "the source's citation; readers draw their own conclusions."
    )
    out.append("")
    out.append("---")
    out.append("")

    # Group by (year, month)
    current_key: tuple[int, int] | None = None
    for e in events:
        if e["sort_year"] == 0:
            continue
        key = (e["sort_year"], e["sort_month"])
        if key != current_key:
            current_key = key
            year_str = str(key[0])
            month_str = [
                "", "January", "February", "March", "April", "May", "June",
                "July", "August", "September", "October", "November", "December"
            ][key[1]] if 1 <= key[1] <= 12 else "Undated"
            out.append("")
            out.append(f"## {month_str} {year_str}")
            out.append("")
        out.append(render_entry(e))

    out.append("")
    out.append("---")
    out.append("")
    out.append(
        "*The Timeline is regenerated from the press index "
        "([press/2026.md](press/2026.md)), the meeting summaries "
        "([summaries_2026.json](https://github.com/b00mhauer/iowa-city-schools-board-archive/blob/main/data/summaries_2026.json)), "
        "and the anchor events file. To add an anchor event, edit "
        "`data/anchor_events_<year>.json` and run `python scripts/build_timeline.py`.*"
    )
    out.append("")
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--press", type=Path, required=True)
    ap.add_argument("--summaries", type=Path, required=True)
    ap.add_argument("--anchors", type=Path, required=True)
    ap.add_argument("--meetings-json", type=Path, required=True,
                    help="Path to ICCSD/all_meetings.json (for meeting dates).")
    ap.add_argument("--year", type=int, required=True)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    press_md = args.press.read_text(encoding="utf-8") if args.press.exists() else ""
    summaries = json.loads(args.summaries.read_text(encoding="utf-8")) \
        if args.summaries.exists() else {}
    anchors = json.loads(args.anchors.read_text(encoding="utf-8")) \
        if args.anchors.exists() else {"events": []}
    all_meetings = json.loads(args.meetings_json.read_text(encoding="utf-8")) \
        if args.meetings_json.exists() else []

    events: list[dict] = []
    events += collect_anchor_events(anchors, args.year)
    events += parse_press_articles(press_md, args.year)
    events += collect_meeting_events(summaries, all_meetings, args.year)

    print(f"Anchor events:  {sum(1 for e in events if e['kind'] == 'anchor')}")
    print(f"Press articles: {sum(1 for e in events if e['kind'] == 'press')}")
    print(f"Meetings:       {sum(1 for e in events if e['kind'] == 'meeting')}")

    out = render_timeline(events, args.year)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(out, encoding="utf-8", newline="\n")
    print(f"Wrote {args.out} ({args.out.stat().st_size:,} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
