"""Convert YouTube-source transcript.json files into readable markdown.

Each meeting folder under ICCSD/<YEAR>/ may contain a `transcript.json`
(produced by yt-dlp scraping the meeting's YouTube recording). Schema:

    {
      "video_id": "...",
      "url": "https://www.youtube.com/watch?v=...",
      "title": "...",
      "language": "en",
      "is_generated": true,
      "source": "yt-dlp",
      "snippets": [{"text": "...", "start": <sec>, "duration": <sec>}, ...]
    }

This script:
  - groups consecutive snippets into paragraphs by detecting time gaps,
  - inserts an HH:MM:SS timestamp at the start of each paragraph that
    links to the YouTube video at that exact second
    (https://youtu.be/<id>?t=<int>),
  - wraps the body in MkDocs frontmatter + a metadata header so it slots
    into the site as a normal page.

Output: docs/meetings/<year>/transcripts/<YYYY-MM-DD>-<slug>.md
"""

from __future__ import annotations

import argparse
import json
import re
from datetime import datetime, timezone
from pathlib import Path


_SLUG_BAD = re.compile(r"[^a-z0-9]+")


def slugify(s: str, max_len: int = 60) -> str:
    s = s.lower()
    s = _SLUG_BAD.sub("-", s).strip("-")
    return s[:max_len].rstrip("-") or "transcript"


def fmt_ts(sec: float) -> str:
    """Format seconds as H:MM:SS (or M:SS for < 1hr)."""
    sec = int(sec)
    h, rem = divmod(sec, 3600)
    m, s = divmod(rem, 60)
    return f"{h}:{m:02d}:{s:02d}" if h else f"{m}:{s:02d}"


def paragraph_breaks(snippets: list[dict], gap_threshold: float = 2.5,
                     max_para_secs: float = 45.0) -> list[list[dict]]:
    """Group snippets into paragraphs by long-ish pauses or natural length.

    yt-dlp emits short overlapping fragments. We coalesce them into
    paragraphs at speech pauses (gap > gap_threshold sec) or every
    max_para_secs to avoid runaway blocks.
    """
    paras: list[list[dict]] = []
    cur: list[dict] = []
    for s in snippets:
        if cur:
            prev = cur[-1]
            prev_end = (prev.get("start") or 0) + (prev.get("duration") or 0)
            gap = (s.get("start") or 0) - prev_end
            cur_span = (s.get("start") or 0) - (cur[0].get("start") or 0)
            if gap >= gap_threshold or cur_span >= max_para_secs:
                paras.append(cur)
                cur = []
        cur.append(s)
    if cur:
        paras.append(cur)
    return paras


def render_transcript(data: dict, meeting_title: str, meeting_date: str,
                      meeting_page: str) -> str:
    """Compose the markdown body for one meeting transcript."""
    title = data.get("title") or meeting_title
    url = data.get("url") or ""
    video_id = data.get("video_id") or ""
    snippets = data.get("snippets") or []

    out: list[str] = []
    out.append("---")
    out.append(f"title: {json.dumps('Transcript — ' + meeting_title)}")
    out.append(f"date: {meeting_date}")
    out.append("---")
    out.append("")
    out.append(f"# {meeting_title} — Transcript")
    out.append("")
    out.append('<div class="meeting-meta" markdown>')
    out.append("")
    out.append(f"**Meeting date:** {meeting_date}")
    out.append("")
    out.append(f"**Meeting page:** [{meeting_title}]({meeting_page})")
    out.append("")
    if url:
        out.append(f"**Video:** [{title}]({url})")
        out.append("")
    out.append('**Source:** YouTube auto-generated captions (machine-transcribed)')
    out.append("")
    out.append("</div>")
    out.append("")
    out.append(
        "!!! warning \"Machine-generated transcript\""
    )
    out.append("")
    out.append(
        "    This transcript was auto-generated by YouTube from the meeting "
        "recording. Speaker names are not attributed and the text contains "
        "the typical errors of speech-to-text — misheard words, missing "
        "punctuation, run-on sentences. **Treat it as a search index and "
        "rough record, not as quotable text.** When something matters, "
        "watch the video directly."
    )
    out.append("")
    out.append("---")
    out.append("")

    if not snippets:
        out.append("_Transcript is empty._")
        return "\n".join(out)

    paras = paragraph_breaks(snippets)
    for para in paras:
        start = para[0].get("start") or 0
        ts = fmt_ts(start)
        text = " ".join((s.get("text") or "").strip() for s in para)
        text = re.sub(r"\s+", " ", text).strip()
        if not text:
            continue
        if video_id:
            anchor = f"https://youtu.be/{video_id}?t={int(start)}"
            out.append(f"**[{ts}]({anchor})** — {text}")
        else:
            out.append(f"**{ts}** — {text}")
        out.append("")

    return "\n".join(out)


def find_transcripts(source_root: Path) -> list[tuple[Path, Path]]:
    """Return (transcript_json_path, meeting_folder) pairs."""
    out: list[tuple[Path, Path]] = []
    for p in source_root.rglob("transcript.json"):
        out.append((p, p.parent))
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source-root", type=Path, required=True,
                    help="ICCSD/<year>/ folder containing per-meeting subfolders")
    ap.add_argument("--year", type=int, required=True)
    ap.add_argument("--out", type=Path, required=True,
                    help="Output dir docs/meetings/<year>/transcripts/")
    args = ap.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    transcripts = find_transcripts(args.source_root)
    print(f"Found {len(transcripts)} transcript.json files")

    written = 0
    index_entries: list[dict] = []
    for tj_path, meeting_dir in transcripts:
        try:
            data = json.loads(tj_path.read_text(encoding="utf-8"))
        except Exception as e:
            print(f"  skip {tj_path}: {e}")
            continue

        # Load meeting.json to get canonical title + date + MID
        meeting_json_path = meeting_dir / "meeting.json"
        if not meeting_json_path.exists():
            print(f"  skip {tj_path}: no meeting.json")
            continue
        meeting = json.loads(meeting_json_path.read_text(encoding="utf-8"))
        mid = meeting.get("ID")
        title = meeting.get("Title", "Meeting")
        # TitleDateTime: "05/26/2026 - 06:00 PM"
        m = re.match(r"(\d{1,2})/(\d{1,2})/(\d{4})", meeting.get("TitleDateTime", ""))
        if not m:
            print(f"  skip MID {mid}: bad TitleDateTime")
            continue
        mm, dd, yy = m.groups()
        date_str = f"{yy}-{int(mm):02d}-{int(dd):02d}"

        slug = slugify(title)
        out_filename = f"{date_str}-{slug}.md"
        meeting_page = f"../{date_str}-{slug}.md"

        md = render_transcript(data, title, date_str, meeting_page)
        (args.out / out_filename).write_text(md, encoding="utf-8")

        index_entries.append({
            "date": date_str,
            "title": title,
            "filename": out_filename,
            "mid": mid,
            "video_url": data.get("url", ""),
        })
        written += 1

    # Write transcripts/index.md
    index_entries.sort(key=lambda x: x["date"], reverse=True)
    idx_lines = [
        f"# {args.year} Meeting Transcripts",
        "",
        f"Machine-generated transcripts of {len(index_entries)} ICCSD board "
        f"meetings from {args.year}, sourced from each meeting's YouTube "
        f"recording. Use these as a search index — the original video is "
        f"the authoritative record.",
        "",
        f"**Pages:** {len(index_entries)} transcripts available "
        f"(newest first).",
        "",
    ]
    for e in index_entries:
        idx_lines.append(
            f"- **{e['date']}** — [{e['title']}]({e['filename']})"
        )
    idx_lines.append("")
    (args.out / "index.md").write_text("\n".join(idx_lines), encoding="utf-8")

    print(f"Wrote {written} transcript pages + index to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
